[project]
name = "mcptool"
version = "1.0-alpha"
dependencies = [
    "mccolors",
    "mcstatus",
    "mcrcon",
    "requests",
    "loguru",
    "pypresence"
]

[project.scripts]
mcptool = "mcptool.__main__:main"